/**
 * ROUTE2 Types
 * 
 * Clean pipeline types for the new search flow
 * Does NOT import V1/V2 orchestrator types
 */

import type { SearchRequest } from '../types/search-request.dto.js';
import type { SearchResponse } from '../types/search-response.dto.js';
import type { LLMProvider } from '../../../llm/types.js';
import type { PreGoogleBaseFilters, FinalSharedFilters } from './shared/shared-filters.types.js';
import type { LangCtx } from './language-enforcement.js';

// Re-export for convenience
export type { SearchRequest, SearchResponse };
export type { PreGoogleBaseFilters, FinalSharedFilters };
export type { LangCtx };

/**
 * ROUTE2 Pipeline Context
 * Minimal context passed through all stages
 */
export interface Route2Context {
  requestId: string;
  traceId?: string;
  sessionId?: string;
  startTime: number;
  debug?: { stopAfter?: 'gate2' | 'intent' | 'route_llm' | 'google' | 'cuisine' | 'post_filters' | 'ranking' | 'response' };

  jobCreatedAt?: number;
  sessionService?: any;
  llmProvider: LLMProvider;
  query?: string;
  userLocation?: {
    lat: number;
    lng: number;
  } | null;
  
  /**
   * LANGUAGE ENFORCEMENT: Single source of truth for all language decisions
   * Set once by Gate2 (or Intent if Gate2 skips), flows through entire pipeline
   * CRITICAL: langCtx.assistantLanguage MUST be present before any assistant WS publish
   */
  langCtx?: LangCtx;
  
  /**
   * @deprecated Use langCtx.uiLanguage instead
   * UI language (from client, for display only)
   */
  uiLanguage?: 'he' | 'en';
  
  userRegionCode?: 'IL' | 'OTHER';
  queryRegionCode?: 'IL' | 'OTHER';
  regionCodeFinal?: 'IL' | 'OTHER';
  sharedFilters?: {
    preGoogle?: PreGoogleBaseFilters;
    final?: FinalSharedFilters;
  };
  google?: {
    servedFrom?: 'cache' | 'google_api';
  };
  timings?: {
    gate2Ms?: number;
    intentMs?: number;
    routeLLMMs?: number;
    baseFiltersMs?: number;
    googleMapsMs?: number;
    postFilterMs?: number;
    responseBuildMs?: number;
  };
}

// Gate2 specific types
export type Gate2Language = 'he' | 'en' | 'ru' | 'ar' | 'fr' | 'es' | 'other';
export type Gate2FoodSignal = 'NO' | 'UNCERTAIN' | 'YES';
export type Gate2Route = 'CONTINUE' | 'ASK_CLARIFY' | 'STOP';

/**
 * Gate2 Stop/Clarify payload
 * Embedded in Gate2Result - contains assistant text generated by Gate2 LLM
 */
export interface Gate2StopPayload {
  type: 'GATE_FAIL' | 'CLARIFY';
  reason: 'NO_FOOD' | 'UNCERTAIN_DOMAIN' | 'MISSING_LOCATION';
  blocksSearch: true;
  suggestedAction: 'ASK_FOOD' | 'ASK_DOMAIN' | 'ASK_LOCATION';
  message: string;
  question: string;
}

/**
 * GATE2 Stage Result
 * Tri-state food classifier with early-stop routing
 */
export interface Gate2Result {
  foodSignal: Gate2FoodSignal;
  language: Gate2Language;
  languageConfidence: number;
  route: Gate2Route;
  confidence: number;
  stop: Gate2StopPayload | null; // NEW: Stop/clarify text from LLM (null when route=CONTINUE)
}

export interface Gate2StageOutput {
  gate: Gate2Result;
  error?: {
    code: string;
    message: string;
    stage: string;
  };
}

// INTENT stage types (router-only)
export type MappingRoute = 'TEXTSEARCH' | 'NEARBY' | 'LANDMARK';

/**
 * Intent routes including clarification request
 * CLARIFY is returned by Intent stage when user location is missing for NEARBY queries
 */
export type IntentRoute = MappingRoute | 'CLARIFY';

/**
 * INTENT Stage Result
 * Router-only decision without extraction
 * Includes language and regionCandidate detection (NOT final region)
 * 
 * NEW: Includes hybrid ordering intent flags (language-agnostic)
 * 
 * IMPORTANT: regionCandidate is a suggestion only - filters_resolved decides the final region
 */
export interface IntentResult {
  route: IntentRoute;
  confidence: number;
  reason: string;
  language: Gate2Language;
  languageConfidence: number;
  assistantLanguage: 'he' | 'en' | 'ru' | 'ar' | 'fr' | 'es'; // REQUIRED: For CLARIFY paths (normalized from language, no 'other')
  regionCandidate: string | null; // ISO-3166-1 alpha-2 candidate (e.g., "IL", "GZ", "FR") or null if invalid - NOT final, must be validated by filters_resolved
  regionConfidence: number;
  regionReason: string;
  regionCode: string | null; // NEW: Region inferred from query text (LLM-first, e.g., "Big Ben" → "GB") - ISO-3166-1 alpha-2 or null
  cityText?: string; // Optional city name for location bias (e.g., "גדרה", "אשקלון")

  // ===== NEW: Hybrid Ordering Intent Flags (Language-Agnostic) =====
  /** Distance/proximity intent detected */
  distanceIntent: boolean;
  /** Explicit "open now" filter requested */
  openNowRequested: boolean;
  /** Price preference intent */
  priceIntent: 'cheap' | 'any';
  /** Quality/special occasion intent */
  qualityIntent: boolean;
  /** Specific occasion type (if detected) */
  occasion: 'romantic' | null;
  /** Cuisine key (canonical identifier) */
  cuisineKey: string | null;

  // ===== CLARIFY Payload (Required, nullable) =====
  /** CLARIFY content from Intent LLM - null when not clarifying, object when clarifying
   * NEW v7: message/question generated by Intent LLM in assistantLanguage
   */
  clarify: {
    reason: 'MISSING_LOCATION' | 'MISSING_FOOD' | 'AMBIGUOUS';
    blocksSearch: true;
    suggestedAction: 'ASK_LOCATION' | 'ASK_FOOD' | 'REFINE';
    message: string;  // User-facing clarification message (generated by Intent LLM)
    question: string; // Follow-up question (generated by Intent LLM)
  } | null;
}

// Intent2 specific types (DEPRECATED - will be removed)
export type Intent2Mode = 'nearby' | 'landmark' | 'textsearch' | 'CLARIFY';;
export type Intent2Reason = 'near_me_phrase' | 'explicit_distance_from_me' | 'landmark_detected' | 'default_textsearch' | 'ambiguous';
export type LandmarkType = 'address' | 'poi' | 'street' | 'neighborhood' | 'area' | 'unknown' | null;
export type RadiusSource = 'explicit' | 'default' | null;

/**
 * INTENT2 Stage Result
 * Extracts food and location intent from query with mode classification
 */
export interface Intent2Result {
  language: Gate2Language;
  mode: Intent2Mode;
  reason: Intent2Reason;
  food: {
    raw: string | null;
    canonicalEn: string | null;
  };
  location: {
    isRelative: boolean;
    text: string | null;
    landmarkText: string | null;
    landmarkType: LandmarkType;
  };
  radiusMeters: number | null;
  radiusSource: RadiusSource;
  queryRegionCode: 'IL' | 'OTHER' | null;
  confidence: number;
}

/**
 * ROUTE_LLM Stage Result
 * Discriminated union of all route-specific mappings
 * Imported from schemas.ts (Zod as source of truth)
 */
export type { RouteLLMMapping } from './stages/route-llm/schemas.js';

/**
 * GOOGLE_MAPS Stage Result
 * Raw results from Google Places API
 */
export interface GoogleMapsResult {
  results: any[];
  providerMethod: 'textSearch' | 'nearbySearch' | 'landmarkPlan';
  durationMs: number;
  servedFrom?: 'cache' | 'google_api'; // Added for cache guard
}
