import { z } from 'zod';

/**
 * Message role in conversation
 */
export type MessageRole = 'user' | 'assistant';

/**
 * Language codes supported
 */
export type Language = 'he' | 'en' | 'fr' | 'es' | 'de' | 'it' | 'ru' | 'ja' | 'zh' | 'pt' | 'ar';

/**
 * Single message in conversation history
 */
export interface DialogueMessage {
    role: MessageRole;
    content: string;
    timestamp: number;
}

/**
 * Quick reply suggestion button
 * Generated dynamically by LLM based on conversation context
 */
export interface Suggestion {
    id: string;
    emoji: string;
    label: string;
    action: 'filter' | 'refine' | 'info' | 'map';
    value?: string; // e.g., "parking", "romantic", "cheap"
}

/**
 * Place item (simplified from Places API)
 */
export interface PlaceItem {
    placeId: string;
    name: string;
    address: string;
    rating?: number;
    userRatingsTotal?: number;
    priceLevel?: number;
    photoUrl?: string;
    website?: string;
    openNow?: boolean;
    location?: { lat: number; lng: number };
}

/**
 * Conversation context (session state)
 * Stored in memory for the duration of the conversation
 */
export interface DialogueContext {
    sessionId: string;
    messages: DialogueMessage[];
    originalQuery?: string;
    baseQuery?: string; // The last base search query (for refinements)
    location?: {
        city?: string;
        coords?: { lat: number; lng: number };
    };
    appliedFilters: string[]; // ["romantic", "parking", "vegan"]
    currentResults: PlaceItem[];
    language: Language;
    detectedInputLanguage?: string; // Cache for detected input language (Step 1.3)
}

/**
 * LLM response structure
 * Generated by LLM using completeJSON with schema validation
 */
export interface DialogueResponse {
    text: string; // Bot message to display
    suggestions: Suggestion[]; // Quick reply buttons (4-6 items)
    shouldSearch: boolean; // True if we need to call Places API
    filters?: string[]; // New filters extracted from user message
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Zod Schemas (for LLM structured output validation)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * Schema for suggestion validation
 */
export const SuggestionSchema = z.object({
    id: z.string().describe('Unique identifier for the suggestion'),
    emoji: z.string().describe('Single emoji character (e.g., 🅿️, 🌹, 💰)'),
    label: z.string().describe('Short label for the button (e.g., "Parking", "Romantic")'),
    action: z.enum(['filter', 'refine', 'info', 'map']).describe('Type of action this suggestion performs'),
    value: z.string().optional().describe('Optional value for filter actions (e.g., "parking", "romantic")'),
});

/**
 * Schema for LLM dialogue response
 * Used with completeJSON to ensure type-safe responses
 */
export const DialogueResponseSchema = z.object({
    text: z.string().describe('Friendly bot message to display to the user'),
    suggestions: z.array(SuggestionSchema).min(4).max(6).describe('4-6 contextual quick reply suggestions'),
    shouldSearch: z.boolean().describe('True if a new search should be performed, false if just clarifying'),
    filters: z.array(z.string()).optional().describe('New filters to apply (e.g., ["romantic", "parking"])'),
});

/**
 * Type inferred from schema
 */
export type DialogueResponseValidated = z.infer<typeof DialogueResponseSchema>;

